const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const accountSchema = new Schema({
    id: {type: Number},
    username: {type:String},
    userpassword: {type:String},
    useremail: {type:String},
    first_name: {type: String},
    last_name: {type: String},
    date_of_birth: {type: String},
    gender: {type: String},
    medicare: {type: String},
    military_id: {type: String},
    weight: {type: String},
    height: {type: String},
    blood_type: {type: String},
    medication_allergies: {type: String},
    food_allergies: {type: String},
    glasses: {type: Boolean},
    dentures: {type: Boolean},
    cane_or_walker: {type: Boolean},
    hearing_aid: {type: Boolean},
    wheelchair: {type: Boolean},
    disabilities: {type: String},
    surgery_name: {type: String},
    surgion: {type: String},
    surgery_date: {type: String},
    surgery_comments: {type: String},
    primary_physician: {type: String},
    primary_physician_address: {type: String},
    primary_physician_phone: {type: String},
    physical_therapist_name: {type: String},
    physical_therapist_address: {type: String},
    physical_therapist_phone: {type: String},
    dentist_name: {type: String},
    dentist_address: {type: String},
    dentist_phone: {type: String},
    other_specialism: {type: String},
    other_name: {type: String},
    other_address: {type: String},
    other_phone: {type: String},
    pharmacy_address: {type: String},
    pharmacy_phone: {type: String},
    insurance_provider: {type: String},
    insurance_number: {type: String},
    medication_name: {type: String},
    medication_purpose: {type: String},
    medication_dose: {type: String},
    medication_instruction: {type: String},
    immunization_name: {type: String},
    immunization_date: {type: String},
    immunization_renewal_date: {type: String},
    event_type: { type: String },
  event_date: { type: String, default: Date.now },
  event_start: { type: String},
  event_end: { type: String},
  event_notes: { type: String},

})

const Account = mongoose.model("Account", accountSchema);
module.exports = Account;